---
- name: Comment out of default source_path
  become: yes
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
    line: '# Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin'
    validate: '/usr/sbin/visudo -cf %s'

- name: Enable env_reset and env_keep for PATH
  become: yes
  blockinfile:
    path: /etc/sudoers
    state: present
    regexp: '^# Defaults   env_keep += "HOME"'
    content: |
      Defaults   env_reset
      Defaults   env_keep += "PATH"
    validate: '/usr/sbin/visudo -cf %s'

- name: Create app dir
  become: yes
  file:
    path: /var/www
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777

- name: Create shared app dir
  become: yes
  file:
    path: /var/www/{{ backend_repository_name }}/shared/config/
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777
  when: "'api-production' or 'api-staging' in group_names"

- name: Create shared settings dir
  become: yes
  file:
    path: /var/www/{{ backend_repository_name }}/shared/config/settings
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777
  when: "'api-production' or 'api-staging' in group_names"

- name: Chmod of application current public
  become: yes
  file:
    path: /var/www/{{ backend_repository_name }}/current/public/
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777
  when: "'api-production' or 'api-staging' in group_names"

- name: Set database.yml
  template:
    src: roles/common/templates/database.yml.j2
    dest: /var/www/{{ backend_repository_name }}/shared/config/database.yml
  when: "'api-production' or 'api-staging' in group_names"

- name: Set master.key
  template:
    src: roles/common/templates/master.key.j2
    dest: /var/www/{{ backend_repository_name }}/shared/config/master.key
  when: "'api-production' or 'api-staging' in group_names"

- name: Set settings/staging.yml
  template:
    src: roles/common/templates/staging.yml.j2
    dest: /var/www/{{ backend_repository_name }}/shared/config/settings/staging.yml
  when: "'api-staging' in group_names"

- name: Set settings/production.yml
  template:
    src: roles/common/templates/production.yml.j2
    dest: /var/www/{{ backend_repository_name }}/shared/config/settings/production.yml
  when: "'api-production' in group_names"
